/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.pp;

import data.Sesija;
import data.operations.PoslovniPartnerOperacija;
import domen.Mesto;
import domen.PoslovniPartner;
import java.awt.Color;
import java.awt.Window;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicBorders;

/**
 *
 * @author student1
 */
public class FPoslovniPartner extends javax.swing.JFrame {

    private Window parent;
    private PoslovniPartnerOperacija ppoperacija;
    
    /**
     * Creates new form FPoslovniPartner
     */
    public FPoslovniPartner(Window parent, PoslovniPartnerOperacija ppoperacija) {
        initComponents();
        initBorders();
        initMestaCombo();
        initErr();
        this.parent = parent;
        this.ppoperacija = ppoperacija;
        jbtnSacuvaj.setText(ppoperacija.vratiImeOperacije());
        if(ppoperacija.vratiImeOperacije().contains("Sacuvaj")) {
            setTitle("Unos novog poslovnog partnera");
        } else if(ppoperacija.vratiImeOperacije().contains("Izmeni")) {
            setTitle("Pregled i izmena poslovnog partnera");
            jtxtMatBroj.setEditable(false);
            jbtnPonisti.setVisible(false);
        }
    }
    
    public FPoslovniPartner(Window parent, PoslovniPartnerOperacija ppoperacija, PoslovniPartner pp) {
        this(parent, ppoperacija);
        jtxtMatBroj.setText(pp.getMatBroj());
        jtxtPIB.setText(pp.getPIB());
        jtxtZiroRacun.setText(pp.getZR());
        jtxtNaziv.setText(pp.getNaziv());
        jtxtUlicaIBroj.setText(pp.getUlicaIBroj());
        Calendar cal = Calendar.getInstance();
        cal.setTime(pp.getDatumOsnivanja());
        jdccDatumOsnivanja.setSelectedDate(cal);
        jcomboMesto.setSelectedItem(pp.getMesto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtPIB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtMatBroj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtZiroRacun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jcomboMesto = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jtxtUlicaIBroj = new javax.swing.JTextField();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnPonisti = new javax.swing.JButton();
        jdccDatumOsnivanja = new datechooser.beans.DateChooserCombo();
        jbtnIzadji = new javax.swing.JButton();
        jlblErrPIB = new javax.swing.JLabel();
        jlblErrMatBr = new javax.swing.JLabel();
        jlblErrNaziv = new javax.swing.JLabel();
        jlblErrZR = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registracija novog poslovnog partnera");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("*PIB:");

        jtxtPIB.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtxtPIB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPIBFocusGained(evt);
            }
        });

        jLabel2.setText("*Maticni broj:");

        jtxtMatBroj.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtxtMatBroj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtMatBrojFocusGained(evt);
            }
        });

        jLabel3.setText("Ziro racun: ");

        jtxtZiroRacun.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtxtZiroRacun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtZiroRacunFocusGained(evt);
            }
        });

        jLabel4.setText("*Naziv:");

        jtxtNaziv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtNazivFocusGained(evt);
            }
        });

        jLabel5.setText("Datum osnivanja:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sediste"));

        jLabel6.setText("Mesto:");

        jcomboMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboMestoActionPerformed(evt);
            }
        });

        jLabel7.setText("Ulica i broj:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtUlicaIBroj)
                    .addComponent(jcomboMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtUlicaIBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnPonisti.setText("Ponisti");
        jbtnPonisti.setToolTipText("");
        jbtnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPonistiActionPerformed(evt);
            }
        });

        jdccDatumOsnivanja.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("DejaVu Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("DejaVu Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("DejaVu Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("DejaVu Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("DejaVu Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("DejaVu Sans", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    jdccDatumOsnivanja.setCalendarBackground(new java.awt.Color(255, 255, 255));
    jdccDatumOsnivanja.setNothingAllowed(false);
    jdccDatumOsnivanja.setFormat(2);
    try {
        jdccDatumOsnivanja.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2015, 2, 4),
            new java.util.GregorianCalendar(2015, 2, 4))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    jdccDatumOsnivanja.setLocale(new java.util.Locale("sr", "BA", ""));

    jbtnIzadji.setText("Izadji");
    jbtnIzadji.setToolTipText("");
    jbtnIzadji.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbtnIzadjiActionPerformed(evt);
        }
    });

    jlblErrPIB.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
    jlblErrPIB.setForeground(new java.awt.Color(204, 0, 0));
    jlblErrPIB.setText(" ");

    jlblErrMatBr.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
    jlblErrMatBr.setForeground(new java.awt.Color(204, 0, 0));
    jlblErrMatBr.setText(" ");

    jlblErrNaziv.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
    jlblErrNaziv.setForeground(new java.awt.Color(204, 0, 0));
    jlblErrNaziv.setText(" ");

    jlblErrZR.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
    jlblErrZR.setForeground(new java.awt.Color(204, 0, 0));
    jlblErrZR.setText(" ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jbtnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                    .addComponent(jbtnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jdccDatumOsnivanja, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(jtxtMatBroj, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(jtxtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(jtxtZiroRacun, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(jtxtPIB, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(jlblErrPIB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblErrMatBr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblErrZR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblErrNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap(23, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtxtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jlblErrPIB)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtxtMatBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jlblErrMatBr)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtxtZiroRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jlblErrZR)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jlblErrNaziv)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jdccDatumOsnivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtnSacuvaj)
                .addComponent(jbtnPonisti)
                .addComponent(jbtnIzadji))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        String pib = jtxtPIB.getText();
        String matBroj = jtxtMatBroj.getText();
        String ziroRacun = jtxtZiroRacun.getText();
        String naziv = jtxtNaziv.getText();
        String ulicaBroj = jtxtUlicaIBroj.getText();
        
        Date date = jdccDatumOsnivanja.getSelectedDate().getTime();
        Mesto m = (Mesto) jcomboMesto.getSelectedItem();
        
        
        boolean isValidated = validateForm(pib, matBroj, ziroRacun, naziv, ulicaBroj);
        if(isValidated) {
            PoslovniPartner pp = new PoslovniPartner();
            pp.setPIB(pib);
            pp.setMatBroj(matBroj);
            pp.setZR(ziroRacun);
            pp.setNaziv(naziv);
            pp.setUlicaIBroj(ulicaBroj);
            pp.setDatumOsnivanja(date);
            pp.setMesto(m);
            
            boolean res;
//            res = dbbroker.dodajPPartnera(pp);
            res = ppoperacija.izvrsiOperaciju(pp);
            if(res) {
                String message = "";
                if(ppoperacija.vratiImeOperacije().contains("Sacuvaj")) {
                    message = "sacuvan";
                } else if(ppoperacija.vratiImeOperacije().contains("Izmeni")) {
                    message = "izmenjen";
                }
                JOptionPane.showMessageDialog(this, "Poslovni partner je uspesno "+message+".", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                dbbroker.prikaziPPartnere();
                resetFields();
                if(ppoperacija.vratiImeOperacije().contains("Izmeni")) {
                    dispose();
                    if(parent != null) {
                        parent.setVisible(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Poslovni partner nije dodat jer vec postoji u bazi.", "Greska!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jtxtNazivFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNazivFocusGained
        jtxtNaziv.setBorder(defaultBorder);
        jtxtNaziv.setToolTipText(null);
        jlblErrNaziv.setText("");
    }//GEN-LAST:event_jtxtNazivFocusGained

    private void jtxtZiroRacunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtZiroRacunFocusGained
        jtxtZiroRacun.setBorder(defaultBorder);
        jtxtZiroRacun.setToolTipText(null);
        jlblErrZR.setText("");
    }//GEN-LAST:event_jtxtZiroRacunFocusGained

    private void jtxtMatBrojFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtMatBrojFocusGained
        jtxtMatBroj.setBorder(defaultBorder);
        jtxtMatBroj.setToolTipText(null);
        jlblErrMatBr.setText("");
    }//GEN-LAST:event_jtxtMatBrojFocusGained

    private void jtxtPIBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPIBFocusGained
        jtxtPIB.setBorder(defaultBorder);
        jtxtPIB.setToolTipText(null);
        jlblErrPIB.setText("");
    }//GEN-LAST:event_jtxtPIBFocusGained

    private void jbtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzadjiActionPerformed
        dispose();
        if(parent != null) {
            parent.setVisible(true);
        }
    }//GEN-LAST:event_jbtnIzadjiActionPerformed

    private void jbtnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPonistiActionPerformed
        resetFields();
    }//GEN-LAST:event_jbtnPonistiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        if(parent != null) {
            parent.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jcomboMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboMestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboMestoActionPerformed

    private boolean validateForm(String pib, String matBroj, String ziroRacun, String naziv, String ulicaBroj) {
        
        boolean isValid = true;
        
        if(pib==null || !(pib.matches("[0-9]{9}"))) {
            jtxtPIB.setBorder(errorBorder);
            jtxtPIB.setToolTipText("PIB mora da ima 9 cifara!");
            jlblErrPIB.setText("PIB mora da ima 9 cifara!");
            isValid = false;
        }
        if(matBroj==null || !(matBroj.matches("[0-9]{12}"))) {
            jtxtMatBroj.setBorder(errorBorder);
            jtxtMatBroj.setToolTipText("Maticni broj mora da ima 12 cifara!");
            jlblErrMatBr.setText("Maticni broj mora da ima 12 cifara!");
            isValid = false;
        }
        if(ziroRacun!=null && !ziroRacun.isEmpty() && !(ziroRacun.matches("([0-9]{3})-([0-9]{3,12})-([0-9]{2})"))) {
            jtxtZiroRacun.setBorder(errorBorder);
            jtxtZiroRacun.setToolTipText("Neispravan format ziro racuna!");
            jlblErrZR.setText("Neispravan format ziro racuna!");
            isValid = false;
        }
        if(naziv==null || naziv.isEmpty()) {
            jtxtNaziv.setBorder(errorBorder);
            jtxtNaziv.setToolTipText("Mora se uneti naziv firme!");
            jlblErrNaziv.setText("Mora se uneti naziv firme!");
            isValid = false;
        }
        
        return isValid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnIzadji;
    private javax.swing.JButton jbtnPonisti;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcomboMesto;
    private datechooser.beans.DateChooserCombo jdccDatumOsnivanja;
    private javax.swing.JLabel jlblErrMatBr;
    private javax.swing.JLabel jlblErrNaziv;
    private javax.swing.JLabel jlblErrPIB;
    private javax.swing.JLabel jlblErrZR;
    private javax.swing.JTextField jtxtMatBroj;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtPIB;
    private javax.swing.JTextField jtxtUlicaIBroj;
    private javax.swing.JTextField jtxtZiroRacun;
    // End of variables declaration//GEN-END:variables
    private Border errorBorder;
    private Border defaultBorder;
    
    private Sesija dbbroker;
    
    private void initBorders() {
        defaultBorder = jtxtPIB.getBorder();
        errorBorder = new BasicBorders.ButtonBorder(Color.red, Color.red, Color.red, Color.red);
    }
    
    private void initMestaCombo() {
        dbbroker = Sesija.getInstance();
        List<Mesto> mesta = dbbroker.vratiSvaMesta();
        for(Mesto m : mesta) {
            jcomboMesto.addItem(m);
        }   
    }
    
    private void resetFields() {
        jtxtMatBroj.setText("");
        jtxtPIB.setText("");
        jtxtNaziv.setText("");
        jtxtZiroRacun.setText("");
        jtxtUlicaIBroj.setText("");
    }
    
    private void initErr() {
        jlblErrMatBr.setText("");
        jlblErrNaziv.setText("");
        jlblErrPIB.setText("");
        jlblErrZR.setText("");
    }
}
