/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.pp;

import data.operations.AzurirajOperacija;
import data.operations.Operacije;
import domen.PoslovniPartner;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author milos
 */
public class FPrikazPP extends javax.swing.JDialog {

    private List<PoslovniPartner> ppartneri;
    
    /**
     * Creates new form FPrikazPP
     */
    public FPrikazPP(java.awt.Frame parent, boolean modal, List<PoslovniPartner> ppartneri) {
        super(parent, modal);
        initComponents();
        this.ppartneri = ppartneri;
        popuniComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcomboPP = new javax.swing.JComboBox();
        jbtnDetalji = new javax.swing.JButton();
        jbtnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz poslovnih partnera");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jbtnDetalji.setText(" Detalji...");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        jbtnIzadji.setText("Izadji");
        jbtnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcomboPP, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnIzadji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDetalji))
                .addGap(41, 41, 41)
                .addComponent(jbtnIzadji)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnIzadjiActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        if(ppartneri.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ne postoje podaci o poslovnim partnerima u bazi.", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            setVisible(false);
            FPoslovniPartner fpp = new FPoslovniPartner(this, new AzurirajOperacija(new Operacije()), (PoslovniPartner) jcomboPP.getSelectedItem());
            fpp.setVisible(true);
        }
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        popuniComboBox();
    }//GEN-LAST:event_formComponentShown

    public void popuniComboBox() {
        jcomboPP.removeAllItems();
        if(ppartneri.isEmpty()) {
            jcomboPP.addItem("Nema poslovnih partnera u bazi.");
            return;
        }
        for(PoslovniPartner pp : ppartneri) {
            jcomboPP.addItem(pp);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JButton jbtnIzadji;
    private javax.swing.JComboBox jcomboPP;
    // End of variables declaration//GEN-END:variables
}
